config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'
  resources :users
  resources :images
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def home
    render 'layouts/home'
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def index
    @images = current_user.images
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:success] = "Image Saved!"
      redirect_to images_path
    else
      flash[:danger] = "Error Occured"
      render 'new'
    end
  end

  def destroy
    image = Image.find(params[:id])
    image.destroy
    flash[:success] = "Image removed"
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :user_id, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash[:danger] = "Invalid email/password"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome, #{@user.email}!"
      redirect_to @user
    else
      flash[:danger] = "An error occurred"
      render 'new'
    end
  end

  def show
    verify_user
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def verify_user
    unless current_user == User.find(params[:id])
      flash[:danger] = "You cannot view other profiles"
      redirect_to user_path(current_user)
    end
  end
end

app/views/images/_form.html.erb
<div class="row">
  <div class="col-xs-6">
    <%= form_for @image, html: {class: 'form-horizontal'} do |f| %>
      <div class="form-group">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.label :image, class: 'col-lg-2' %>
        <%= f.file_field :image, class: 'col-lg-10' %>
      </div>
      <div class="form-group">
        <%= f.label :description, class: 'col-lg-2' %>
        <%= f.text_field :description, class: 'col-lg-10' %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'col-lg-offset-2 btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/images/index.html.erb
<div class="row">
  <div class="col-xs-12 images">
      <% @images.each do |img| %>
        <div class="col-xs-4">
          <%= img.description %><span class='right-align'><%= link_to 'X', image_path(img), method: :delete, class: 'btn btn-primary btn-xs' %></span>
          <%= image_tag(img.image) %>
        </div>
      <% end %>
  </div>
</div>

app/views/images/new.html.erb
<%= render 'form' %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Image Uploader</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Images<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Add Images', new_image_path %></li>
              <li><%= link_to 'All Images', images_path %></li>
            </ul>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up', signup_path %></li>
          <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imageboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 bordered img-back tall">

    </div>
    <div class="col-xs-2 bordered img-back small">

    </div>
    <div class="col-xs-2 bordered img-back medium">

    </div>
    <div class="col-xs-2 bordered img-back small">

    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 bordered img-back small">

    </div>
    <div class="col-xs-2 bordered img-back small">

    </div>
    <div class="col-xs-4 bordered img-back small">

    </div>
    <div class="col-xs-2 bordered img-back small">

    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-xs-6">
    <%= form_for @user, html: {class: 'form-horizontal'} do |f| %>
      <div class="form-group">
        <%= f.label :email, class: 'col-lg-2' %>
        <%= f.text_field :email, class: 'col-lg-10' %>
      </div>
      <div class="form-group">
        <%= f.label :password, class: 'col-lg-2' %>
        <%= f.password_field :password, class: 'col-lg-2' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, class: 'col-lg-2' %>
        <%= f.password_field :password_confirmation, class: 'col-lg-2' %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'col-lg-offset-2 btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-6">
  </div>
</div>